#!/bin/bash

rules_file="$1"
packets=$(cat)
fixed_rules=$(sed -e 's/ //g' -e '/^$/d' -e 's/#.*//' -e 's/^,+//' -e 's/,+$//' -e 's/,+/,/g' "$rules_file" | grep -v '^$')

output=''

IFS=$'\n' read -d '' -r -a rule_array <<< "$fixed_rules"

for line in "${rule_array[@]}"; do
  all_valid="$packets"
  IFS=',' read -ra rule_parts <<< "$line"

  for rule in "${rule_parts[@]}"; do
    all_valid=$(./firewall.exe "$rule" <<< "$all_valid")
  done

  output+="\n$all_valid"
done

output=$(echo -e "$output" | grep -v '^$' | tr -d ' ' | sort -u)

echo -e "$output"
