#!/bin/bash

rules_file="$1"
packets=$(cat)
fixed_rules=$(awk -F"[[:space:],#]+" '!/^ *$/ && !/^#/ { print $0 }' "$rules_file")

output=''

while IFS= read -r line; do
  all_valid="$packets"
  IFS=',' read -ra rule_array <<< "$line"

  for rule in "${rule_array[@]}"; do
    all_valid=$(echo "$all_valid" | ./firewall.exe "$rule")
  done

  output+="\n$all_valid"
done <<< "$fixed_rules"

output=$(echo -e "$output" | awk 'NF' | sort -u)

echo -e "$output"
